### ISSUE TITLE
Mark PostcodeResult as Serializable

### ISSUE THREAD

**Issue by Philo** [markembling/MarkEmbling.PostcodesIO#3]
Hi,

I have a very small feature request.

I'm using your library to interact with the postcodes.io API and I'm looking to add redis caching to my lookups to prevent any excessive API calls, ideally I would like to simply serialise the `PostcodeResult`.  To easily do this it would be useful if the `PostcodeResult` class was marked as `[Serializable]`.

**Comment by markembling** [comment]
That sounds fine to me. Is that the extent of the changes you'd need?

**Comment by Philo** [comment]
Yea, as a single, simple addition.

**Comment by markembling** [comment]
No worries. I've made that change and pushed out version 0.0.3 to NuGet.

**Comment by Philo** [comment]
Thanks
