### ISSUE TITLE
RestSharp update breaks client.Lookup(Postcode)

### ISSUE THREAD

**Issue by belliez** [markembling/MarkEmbling.PostcodesIO#7]
Updating to latest RestSharp via Nuget breaks functionality.  Latest RestSharp requires minimum of .Net 4.5.2

**Comment by markembling** [comment]
Current version also requires minimum of .NET 4.5.2 (as of 0.0.6).
Next version (1.0.0) will target both .NET standard 2.0 and .NET 4.5.2.
