### ISSUE TITLE
RestSharp update 106.5 breaks this package

### ISSUE THREAD

**Issue by steveglen** [markembling/MarkEmbling.PostcodesIO#9]
See https://github.com/restsharp/RestSharp/issues/1198

In PostcodesIO the following error occurs when RestSharp is upgraded from 106.4 to 106.5:

System.MissingMethodException: Method not found: 'Void RestSharp.RestRequest..ctor(System.String, RestSharp.Method)'.
   at MarkEmbling.PostcodesIO.PostcodesIOClient.CreateLookupRequest(String postcode)
   at MarkEmbling.PostcodesIO.PostcodesIOClient.LookupAsync(String postcode)

Fixed for me by downgrading RestSharp back to 106.4.2 (in case this helps others)

**Comment by markembling** [comment]
Sorry to have not responded to this until now. It looks like jumping to the latest RestSharp doesn't have the same issue (upgrading to that for me didn't break anything). In any case, the next release (v1.0.0) will depend on the latest version.

**Comment by markembling** [comment]
Oh, also, ignore the 'duplicate' label being added. Clumsy fingers.
